'use strict'

const ACCESS_TOKEN_REQUEST_HEADER_KEY = 'X-Access-Token'
const ACCESS_TOKEN_RESPONSE_HEADER_KEY = 'X-Access-Token'

const SESSION_ID_REQUEST_HEADER_KEY = 'X-Session-ID'
const SESSION_ID_RESPONSE_HEADER_KEY = 'X-Session-ID'

const REQUEST_ID_REQUEST_HEADER_KEY = 'X-Request-ID'

const API_KEY_REQUEST_HEADER_KEY = 'X-API-Key'

const APP_UID_REQUEST_HEADER_KEY = 'X-App-UID'
const APP_UID_RESPONSE_HEADER_KEY = 'X-App-UID'

const ENCRYPTION_KEY_REQUEST_HEADER = 'X-API-Encryption-Key'
const CLIENT_ID_KEY_REQUEST_HEADER = 'X-API-Client-Id'
const CLIENT_ID = 'BROWSER'

const TIMEOUT = 3000

const DEFAULT_CONSTANTS = {
  ACCESS_TOKEN_REQUEST_HEADER_KEY,
  ACCESS_TOKEN_RESPONSE_HEADER_KEY,

  SESSION_ID_REQUEST_HEADER_KEY,
  SESSION_ID_RESPONSE_HEADER_KEY,

  REQUEST_ID_REQUEST_HEADER_KEY,

  API_KEY_REQUEST_HEADER_KEY,

  APP_UID_REQUEST_HEADER_KEY,
  APP_UID_RESPONSE_HEADER_KEY,

  ENCRYPTION_KEY_REQUEST_HEADER,
  CLIENT_ID_KEY_REQUEST_HEADER,
  CLIENT_ID,

  TIMEOUT
}

export default DEFAULT_CONSTANTS

export const CONTEXT_MAP = {
  CONSTANTS: 'CONSTANTS',
  CONFIG: 'CONFIG',
  API_KEY: 'API_KEY',
  CLIENT_ID: 'CLIENT_ID',
  SESSION_ID: 'SESSION_ID',
  PUBLIC_KEY: 'PUBLIC_KEY',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  APP_UID: 'APP_UID',
  REQUEST_ID: 'REQUEST_ID'
}

export const ROTATE_VALUE_KEYS = [
  CONTEXT_MAP.ACCESS_TOKEN,
  CONTEXT_MAP.PUBLIC_KEY
]
