export default function getContext (CONFIG, CONSTANTS) {
  const {
    ACCESS_TOKEN_REQUEST_HEADER_KEY,
    ACCESS_TOKEN_RESPONSE_HEADER_KEY,

    SESSION_ID_REQUEST_HEADER_KEY,
    SESSION_ID_RESPONSE_HEADER_KEY,

    APP_UID_REQUEST_HEADER_KEY,
    APP_UID_RESPONSE_HEADER_KEY
  } = CONSTANTS

  const STORE_KEYS_MAP = {
    SESSION_ID: 'SESSION_ID',
    ACCESS_TOKEN: 'ACCESS_TOKEN',
    APP_UID: 'APP_UID',
    PUBLIC_KEY: 'PUBLIC_KEY'
  }
  const CUSTOM_HEADER_CONFIG = [
    {
      REQUEST_HEADER_KEY: SESSION_ID_REQUEST_HEADER_KEY,
      RESPONSE_HEADER_KEY: SESSION_ID_RESPONSE_HEADER_KEY,
      STORE_KEY: STORE_KEYS_MAP.SESSION_ID
    },
    {
      REQUEST_HEADER_KEY: ACCESS_TOKEN_REQUEST_HEADER_KEY,
      RESPONSE_HEADER_KEY: ACCESS_TOKEN_RESPONSE_HEADER_KEY,
      STORE_KEY: STORE_KEYS_MAP.ACCESS_TOKEN
    },
    {
      REQUEST_HEADER_KEY: APP_UID_REQUEST_HEADER_KEY,
      RESPONSE_HEADER_KEY: APP_UID_RESPONSE_HEADER_KEY,
      STORE_KEY: STORE_KEYS_MAP.APP_UID
    }
  ]

  const context = {
    CONSTANTS,
    CONFIG,
    STORE_KEYS_MAP,
    store: {},
    CUSTOM_HEADER_CONFIG
  }

  return context
}
